### ISSUE TITLE
Typografia a crear

### ISSUE THREAD

**Issue by manuelbenitez** [fs4-equipo1/ReplicaWeb2#2]
**Titulo**
![image](https://github.com/fs4-equipo1/ReplicaWeb2/assets/20058638/a93f261f-35fd-488e-ae3b-30a8ee8e59d4)

El texto es el mismo, solo cambia de color.

**Cards de texto**
![image](https://github.com/fs4-equipo1/ReplicaWeb2/assets/145432136/0b947f91-35bf-408d-883a-af3da9aefa20)

Cada texto es distinto.

**Footer Titulo y _links**_
![image](https://github.com/fs4-equipo1/ReplicaWeb2/assets/145432136/9c272e5a-5395-498d-bda3-3b68534baedf)

**Comment by Ebenitez03** [comment]
Está terminado. Iván cogió las tipografías de la página web, Luis convirtió los documentos en algo utilizable
